import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  weight: "800",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body>{children}</body>
    </html>
  );
}
